# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FingerprintApp(object):
    def setupUi(self, FingerprintApp):
        FingerprintApp.setObjectName("FingerprintApp")
        FingerprintApp.resize(800, 439)
        FingerprintApp.setStyleSheet("font-size: 16px;\n"
"          padding: 10px;\n"
"          background: #F5F5F5;\n"
"          color: #000000;\n"
"          font-family: Arial, sans-serif;")
        self.centralwidget = QtWidgets.QWidget(parent=FingerprintApp)
        self.centralwidget.setObjectName("centralwidget")
        self.imageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(270, 140, 256, 288))
        self.imageLabel.setMinimumSize(QtCore.QSize(256, 288))
        self.imageLabel.setStyleSheet("border: 3px solid #2196F3;\n"
"          border-radius: 10px;\n"
"          background: #FFFFFF;\n"
"          font-size: 24px;\n"
"          color: #000000;\n"
"          font-weight: bold;\n"
"          padding: 5px;")
        self.imageLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.matchStatusDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.matchStatusDisplay.setGeometry(QtCore.QRect(270, 10, 256, 111))
        self.matchStatusDisplay.setMinimumSize(QtCore.QSize(0, 61))
        self.matchStatusDisplay.setStyleSheet("""
            QTextEdit {
                font-size: 18px;
                padding: 10px;
                border-radius: 8px;
                background: #FFFFFF;
                border: 2px solid #4CAF50;
                color: #000000;
                font-weight: bold;
                font-family: 'Roboto', sans-serif;
            }
        """)
        self.matchStatusDisplay.setReadOnly(True)
        self.matchStatusDisplay.setHtml("""
            <div style='font-size: 18px; font-weight: bold; color: #000000;'>
                🔍 Match Status:
            </div>
        """)
        self.matchStatusDisplay.setObjectName("matchStatusDisplay")
        self.spoofStatusDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.spoofStatusDisplay.setGeometry(QtCore.QRect(540, 10, 241, 111))
        self.spoofStatusDisplay.setMinimumSize(QtCore.QSize(0, 51))
        self.spoofStatusDisplay.setStyleSheet("""
            QTextEdit {
                font-size: 18px;
                padding: 10px;
                border-radius: 8px;
                background: #FFFFFF;
                border: 2px solid #F44336;
                color: #000000;
                font-weight: bold;
                font-family: 'Roboto', sans-serif;
            }
        """)
        self.spoofStatusDisplay.setReadOnly(True)
        self.spoofStatusDisplay.setHtml("""
            <div style='font-size: 18px; font-weight: bold; color: #000000;'>
                🛡️ Spoof Status:
            </div>
        """)
        self.spoofStatusDisplay.setObjectName("spoofStatusDisplay")
        self.resultsDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.resultsDisplay.setGeometry(QtCore.QRect(20, 10, 241, 271))
        self.resultsDisplay.setMinimumSize(QtCore.QSize(0, 150))
        self.resultsDisplay.setStyleSheet("""
            QTextEdit {
                font-size: 16px;
                border: 2px solid #2196F3;
                padding: 5px;
                border-radius: 8px;
                background: #FFFFFF;
                color: #333333;
                font-family: 'Roboto Mono', 'Segoe UI Emoji', monospace;
                text-align: left;
            }
            QScrollBar:vertical {
                border: none;
                background: #F0F0F0;
                width: 12px;
                margin: 0px;
            }
            QScrollBar::handle:vertical {
                background: #C0C0C0;
                min-height: 20px;
                border-radius: 6px;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
        """)
        self.resultsDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.resultsDisplay.setReadOnly(True)
        self.resultsDisplay.setHtml("""
            <div style='font-size: 16px; color: #333333;'>
                📋 System Status:
            </div>
        """)
        self.resultsDisplay.setObjectName("resultsDisplay")
        self.sensorTypeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sensorTypeButton.setGeometry(QtCore.QRect(540, 140, 239, 51))
        self.sensorTypeButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #9C27B0;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #7B1FA2;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #BA68C8;\n"
"          }")
        self.sensorTypeButton.setObjectName("sensorTypeButton")
        self.spoofToggleButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.spoofToggleButton.setGeometry(QtCore.QRect(540, 219, 239, 51))
        self.spoofToggleButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #FF9800;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #F57C00;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #FFB74D;\n"
"          }")
        self.spoofToggleButton.setObjectName("spoofToggleButton")
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(540, 298, 239, 51))
        self.searchButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #2196F3;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #1976D2;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #64B5F6;\n"
"          }")
        self.searchButton.setObjectName("searchButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(540, 377, 239, 51))
        self.exitButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #F44336;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #D32F2F;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #E57373;\n"
"          }")
        self.exitButton.setObjectName("exitButton")
        self.enrollButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enrollButton.setGeometry(QtCore.QRect(20, 300, 239, 51))
        self.enrollButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #4CAF50;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #388E3C;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #81C784;\n"
"          }")
        self.enrollButton.setObjectName("enrollButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(20, 377, 239, 51))
        self.deleteButton.setStyleSheet("QPushButton {\n"
"            padding: 10px;\n"
"            font-size: 18px;\n"
"            background: #F44336;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-weight: bold;\n"
"            font-family: Arial, sans-serif;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background: #D32F2F;\n"
"          }\n"
"          QPushButton:disabled {\n"
"            background: #E57373;\n"
"          }")
        self.deleteButton.setObjectName("deleteButton")
        FingerprintApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(FingerprintApp)
        #self.sensorTypeButton.clicked.connect(FingerprintApp.toggle_sensor_type) # type: ignore
        self.deleteButton.clicked.connect(FingerprintApp.open_delete_dialog) # type: ignore
        self.enrollButton.clicked.connect(FingerprintApp.open_enroll_dialog) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FingerprintApp)

    def retranslateUi(self, FingerprintApp):
        _translate = QtCore.QCoreApplication.translate
        FingerprintApp.setWindowTitle(_translate("FingerprintApp", "Fingerprint Liveness Detection"))
        self.imageLabel.setText(_translate("FingerprintApp", "Scanned Image Here"))
        self.matchStatusDisplay.setPlaceholderText(_translate("FingerprintApp", "Match Status: Matched or Not Matched"))
        self.spoofStatusDisplay.setPlaceholderText(_translate("FingerprintApp", "Spoof Status: Live or Fake"))
        self.resultsDisplay.setPlaceholderText(_translate("FingerprintApp", "System operations and status will appear here..."))
        self.sensorTypeButton.setText(_translate("FingerprintApp", "Sensor Type: Capacitive"))
        self.spoofToggleButton.setText(_translate("FingerprintApp", "Toggle Anti Spoof"))
        self.searchButton.setText(_translate("FingerprintApp", "Search"))
        self.exitButton.setText(_translate("FingerprintApp", "Exit"))
        self.enrollButton.setText(_translate("FingerprintApp", "Enroll"))
        self.deleteButton.setText(_translate("FingerprintApp", "Delete"))

    def update_sensor_type_button(self, sensor_type):
        """Update the sensor type button text"""
        _translate = QtCore.QCoreApplication.translate
        self.sensorTypeButton.setText(_translate("FingerprintApp", f"Sensor Type: {sensor_type}"))
        self.sensorTypeButton.repaint()  # Force immediate update
